### PR TITLE
Simplify out the code.

### PR DESCRIPTION
**Pull request by PoomSmart**
Hooking up the deepest method (function). This will really let you be able to dictate in any languages. (If supported by server)
:)

### CODE REVIEW

**Comment by r-plus** [comment]
Thx. 
I'll look at later.

**Comment by r-plus** [comment]
Your code destroy purpose of Dictator.
 Dictator purpose is that force to specific dictation language even if using any language keyboard.

**Comment by PoomSmart** [comment]
I think it does (break purposes) only if I remove your old codes. Yes, I did in this pull request. But, anyway, the old version, this forcing just let you have dictation key in such keyboard in specific language, but you may not be able to really dictate in that language, because the system doesn't really support it (that NSArray function won't return some languages in the supported list), and only does when system called those your removed methods. So, does the dictation functionality important to your project? If not, it's ok to reject this pull request. ;)

**Comment by r-plus** [comment]
Probably you are misunderstanding purpose of Dictator.
Dictator use case like this.

User only use dictation to input japanese, but dictation language depending using keyboard type.
User want dictation as japanese even if using english keyboard.
Dictator provide feature for that case. If user set japanese, always dictated as japanese all type of keyboard.

**Comment by PoomSmart** [comment]
Okay I got it. Sorry for any inconvenience.

**Pull request closed without merging**
